spring:
 # Налаштування обробки мультимедійних файлів
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
 # Налаштування джерела даних (DataSource)
  datasource:
    url: jdbc:postgresql://localhost:5433/inventoryOfShop
    username: superuser
    password: superuser
 # Налаштування JPA (Java Persistence API)
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
# Налаштування базового шляху для зберігання зображень
image:
  basepath: product_images
